# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Learning Objective

At the end of this experiment, you will be able to:

* perform Data preprocessing

In [ ]:
#@title  Mini Hackathon Walkthrough
from IPython.display import HTML

HTML("""<video width="640" height="420" controls>
  <source src="https://cdn.talentsprint.com/talentsprint/archives/sc/aiml/aiml_batch_15/preview_videos/Mini_Hackathon_Data_Munging_Briefing.mp4" type="video/mp4">
</video>
""")

## Problem Statement

We will be using district wise demographics, enrollments, and teacher indicator data to predict whether the literacy rate is high/ medium/ low in each district.

### Data Preprocessing

Data preprocessing is an important step in solving every machine learning problem. Most of
the datasets used with Machine Learning problems need to be processed / cleaned / transformed
so that a Machine Learning algorithm can be trained on it.

There are different steps involved in Data Preprocessing. These steps are as follows:

    1. Data Cleaning → In this step the primary focus is on
        - Handling missing data
        - Handling noisy data
        - Detection and removal of outliers
    
    2. Data Integration → This process is used when data is gathered from various data sources and data are combined to form consistent data.
    This data after performing cleaning is used for analysis.
    
    3. Data Transformation → In this step we will convert the raw data into a specified format according to the need of the model we are building.
    There are many options used for transforming the data as below:
        - Normalization
        - Aggregation
        - Generalization
        
    4. Data Reduction → Following data transformation and scaling, the redundancy within the data is removed and is organized efficiently.

### Total Marks  = 20

In [ ]:
# @title Download the datasets
from IPython import get_ipython

ipython = get_ipython()

notebook="U1_MH1_Data_Munging" #name of the notebook

def setup():
    from IPython.display import HTML, display
    ipython.magic("sx wget https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/B15_Data_Munging.zip")
    ipython.magic("sx unzip B15_Data_Munging.zip")
    print("Data downloaded successfully")
    return

setup()

Data downloaded successfully

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!ls

B15_Data_Munging.zip
Districtwise_Basicdata.csv
Districtwise_Enrollment_details_indicator.csv
Districtwise_Teacher_indicator.csv
drive
sample_data

## Exercise 1 - Load and Explore the Data (3 Marks)
1. We have three different files

  * Districtwise_Basicdata.csv
  * Districtwise_Enrollment_details_indicator.csv
  * Districtwise_Teacher_indicator.csv

  These files contain the necessary data to solve the problem. <br>

2. Load the files based on **team allocation** mentioned below. Observe the header level details, data records while loading the data.
  
  Hint : Use read_csv from pandas with [skiprows or header](https://towardsdatascience.com/import-csv-files-as-pandas-dataframe-with-skiprows-skipfooter-usecols-index-col-and-header-fbf67a2f92a) options.

3. Read the columns of the dataset and rename them if required.

  Hint : Rename column names (if any) using the following [link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html).

Team allocation for dataset selection

    Team A = 1,3,5,7,9,11,13,15
        Districtwise_Basicdata.csv
        Districtwise_Enrollment_details_indicator.csv

    Team B = 2,4,6,8,10,12,14
        Districtwise_Basicdata.csv
        Districtwise_Teacher_indicator.csv

In [ ]:
# Importing all the required packages and add necessary imports if required
import pandas as pd
import numpy as np

In [ ]:
# YOUR CODE HERE for loading and exploring the datasets
df1 = pd.read_csv('/content/Districtwise_Basicdata.csv',skiprows=1,header=0)
df1.columns = df1.columns.str.strip().str.lower()
df1.head()
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1324 entries, 0 to 1323
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           1324 non-null   object
 1   statecd        1324 non-null   int64
 2   statename      1324 non-null   object
 3   distcd         1324 non-null   int64
 4   distname       1324 non-null   object
 5   blocks         1324 non-null   int64
 6   clusters       1324 non-null   int64
 7   villages       1324 non-null   int64
 8   totschools     1324 non-null   int64
 9   totpopulation  1268 non-null   float64
 10  p_06_pop       1266 non-null   float64
 11  p_urb_pop      1262 non-null   float64
 12  sexratio       1268 non-null   float64
 13  sexratio_06    1266 non-null   float64
 14  growthrate     1268 non-null   float64
 15  p_sc_pop       1256 non-null   float64
 16  p_st_pop       1256 non-null   float64
 17  overall_lit    1268 non-null   object
 18  female_lit     1268 non-null   float64
dtypes: float64(9), int64(6), object(4)
memory usage: 196.7+ KB

In [ ]:
df2 = pd.read_csv('/content/Districtwise_Teacher_indicator.csv',skiprows=3,header=0)
df2 = df2.rename(columns={"ac_year": "year"})
df2.columns = df2.columns.str.strip().str.lower()
df2.head()
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1324 entries, 0 to 1323
Columns: 181 entries, statecd to tch_nontch
dtypes: int64(178), object(3)
memory usage: 1.8+ MB

## Exercise 2  - Data Integration (3 Marks)

As the required data is present in different datasets, we need to **integrate both to make a single dataframe/dataset**.
  * For integrating the datasets, create a unique identifier for each row in both the dataframes so that it can be used to map the data in different files.
   
    * Combine year, state code, district code columns and form a new unique identifier column, refer to this [link](https://stackoverflow.com/questions/33098383/merge-multiple-column-values-into-one-column-in-python-pandas).
    * Set the identifier column as the index for each dataframe.

    * Integrate the dataframes using the above index
     
     Hint: For merging or joining the datasets, refer to this [link](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html)

**Example:** Data of the district Anantapur in Andrapradesh, which is present in different files should form a single row after integrating the datasets

In [ ]:
# YOUR CODE HERE for integrating the datasets
# Create a unique identifier for df1
df1['Unique_ID'] = df1['year'].astype(str) + '_' + df1['statecd'].astype(str) + '_' + df1['distcd'].astype(str)

# Create a unique identifier for df2
df2['Unique_ID'] = df2['year'].astype(str) + '_' + df2['statecd'].astype(str) + '_' + df2['distcd'].astype(str)

# Set 'Unique_ID' as the index for both dataframes
df1.set_index('Unique_ID', inplace=True)
df2.set_index('Unique_ID', inplace=True)

# Merge the dataframes based on their index
df_merged = pd.merge(df1, df2, left_index=True, right_index=True, how='inner')

# Display the head of the merged dataframe and its info
display(df_merged.head(3))
df_merged.info()

# Display all column names of the merged DataFrame
print(df_merged.columns.tolist())

,year_x,statecd_x,statename_x,distcd_x,distname_x,blocks,clusters,villages,totschools,totpopulation,p_06_pop,p_urb_pop,sexratio,sexratio_06,growthrate,p_sc_pop,p_st_pop,overall_lit,female_lit,statecd_y,statename_y,distcd_y,distname_y,year_y,tch_govt1,tch_govt2,tch_govt3,tch_govt4,tch_govt5,tch_govt6,tch_govt7,tch_govt9,tch_pvt1,tch_pvt2,tch_pvt3,tch_pvt4,tch_pvt5,tch_pvt6,tch_pvt7,tch_pvt9,tch_un1,tch_un2,tch_un3,tch_un4,tch_un5,tch_un6,tch_un7,tch_un9,tch_bs1,tch_bs2,tch_bs3,tch_bs4,tch_bs5,tch_bs6,tch_bs7,tch_bs_p,tch_s1,tch_s2,tch_s3,tch_s4,tch_s5,tch_s6,tch_s7,tch_s_p,tch_hs1,tch_hs2,tch_hs3,tch_hs4,tch_hs5,tch_hs6,tch_hs7,tch_hs_p,tch_grad1,tch_grad2,tch_grad3,tch_grad4,tch_grad5,tch_grad6,tch_grad7,tch_grad_p,tch_pgrad1,tch_pgrad2,tch_pgrad3,tch_pgrad4,tch_pgrad5,tch_pgrad6,tch_pgrad7,tch_pgrad_p,tch_mph1,tch_mph2,tch_mph3,tch_mph4,tch_mph5,tch_mph6,tch_mph7,tch_mph_p,tch_pd1,tch_pd2,tch_pd3,tch_pd4,tch_pd5,tch_pd6,tch_pd7,tch_pd_p,tch_eduqual_nr1,tch_eduqual_nr2,tch_eduqual_nr3,tch_eduqual_nr4,tch_eduqual_nr5,tch_eduqual_nr6,tch_eduqual_nr7,tch_eduqual_nr_p,tch_m1,tch_m2,tch_m3,tch_m4,tch_m5,tch_m6,tch_m7,tch_f1,tch_f2,tch_f3,tch_f4,tch_f5,tch_f6,tch_f7,tch_nr1,tch_nr2,tch_nr3,tch_nr4,tch_nr5,tch_nr6,tch_nr7,tch_m_p1,tch_m_p2,tch_m_p3,tch_m_p4,tch_m_p5,tch_m_p6,tch_m_p7,tch_f_p1,tch_f_p2,tch_f_p3,tch_f_p4,tch_f_p5,tch_f_p6,tch_f_p7,tch_nr_p1,tch_nr_p2,tch_nr_p3,tch_nr_p4,tch_nr_p5,tch_nr_p6,tch_nr_p7,tch_sc_m1,tch_sc_m2,tch_sc_m3,tch_sc_m4,tch_sc_m5,tch_sc_m6,tch_sc_m7,tch_sc_f1,tch_sc_f2,tch_sc_f3,tch_sc_f4,tch_sc_f5,tch_sc_f6,tch_sc_f7,tch_st_m1,tch_st_m2,tch_st_m3,tch_st_m4,tch_st_m5,tch_st_m6,tch_st_m7,tch_st_f1,tch_st_f2,tch_st_f3,tch_st_f4,tch_st_f5,tch_st_f6,tch_st_f7,trn_tch_m1,trn_tch_m2,trn_tch_m3,trn_tch_m4,trn_tch_m5,trn_tch_m6,trn_tch_m7,trn_tch_f1,trn_tch_f2,trn_tch_f3,trn_tch_f4,trn_tch_f5,trn_tch_f6,trn_tch_f7,prof_trn_tch_r,prof_trn_tch_p,days_nontch,tch_nontch
Unique_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2012-13_35_3501,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3501,ANDAMANS ...,3,16,83,212,237586.0,23616.05,55.89,874.0,980.0,13.97,0.0,1.72,High,84.52,35,ANDAMAN & NICOBAR ISLANDS ...,3501,ANDAMANS ...,2012-13,329,429,1097,0,127,432,0,0,308,117,317,0,0,83,0,0,0,0,0,0,0,0,0,0,15,9,13,0,0,4,0,11,9,10,25,0,2,20,0,5,241,181,244,0,29,160,0,94,138,208,475,0,48,194,0,80,64,114,540,0,43,112,0,57,2,5,72,0,3,8,0,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,116,166,535,0,62,161,0,353,361,835,0,63,337,0,0,0,0,0,0,0,0,19,6,8,0,0,0,0,149,13,36,0,2,17,0,0,0,0,0,0,0,0,0,0,4,0,0,2,0,0,0,1,0,0,0,0,4,3,16,0,0,8,0,11,5,18,0,1,11,0,69,97,64,0,14,66,0,134,176,135,0,22,103,0,2968,228,12,519
2012-13_35_3503,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3503,MIDDLE AND NORTH ANDAMANS ...,3,13,76,181,105539.0,11651.51,2.60,925.0,975.0,-0.07,0.0,0.72,High,79.39,35,ANDAMAN & NICOBAR ISLANDS ...,3503,MIDDLE AND NORTH ANDAMANS ...,2012-13,305,285,194,95,268,175,0,0,103,31,0,0,0,15,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,3,7,4,3,2,1,2,0,0,255,110,33,22,6,63,0,37,55,95,56,31,69,66,0,71,22,35,80,29,144,40,0,94,0,3,3,5,17,1,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,177,123,81,56,142,74,0,163,124,94,33,95,99,0,0,0,0,0,0,0,0,19,32,3,1,5,2,0,49,37,16,5,26,15,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,6,2,7,0,0,2,2,3,0,4,2,0,126,79,32,8,45,37,0,84,85,40,3,28,60,0,1249,203,8,362
2012-13_35_3502,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3502,NICOBARS ...,3,8,42,58,36819.0,4226.82,0.00,778.0,961.0,-12.48,0.0,64.28,High,70.70,35,ANDAMAN & NICOBAR ISLANDS ...,3502,NICOBARS ...,2012-13,110,95,56,0,135,114,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,26,7,8,0,3,10,0,0,72,29,7,0,2,34,0,8,7,36,13,0,34,41,0,26,3,7,14,0,60,6,0,45,0,1,4,0,7,4,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,42,35,28,0,65,42,0,67,45,19,0,41,53,0,0,0,0,0,0,0,0,1,10,3,0,12,3,0,8,5,6,0,17,16,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,33,29,18,0,27,27,0,53,32,16,0,28,40,0,36,25,18,0,22,31,0,58,29,23,0,17,46,0,430,78,20,28

<class 'pandas.core.frame.DataFrame'>
Index: 1324 entries, 2012-13_35_3501 to 2013-14_19_1904
Columns: 200 entries, year_x to tch_nontch
dtypes: float64(9), int64(184), object(7)
memory usage: 2.1+ MB
['year_x', 'statecd_x', 'statename_x', 'distcd_x', 'distname_x', 'blocks', 'clusters', 'villages', 'totschools', 'totpopulation', 'p_06_pop', 'p_urb_pop', 'sexratio', 'sexratio_06', 'growthrate', 'p_sc_pop', 'p_st_pop', 'overall_lit', 'female_lit', 'statecd_y', 'statename_y', 'distcd_y', 'distname_y', 'year_y', 'tch_govt1', 'tch_govt2', 'tch_govt3', 'tch_govt4', 'tch_govt5', 'tch_govt6', 'tch_govt7', 'tch_govt9', 'tch_pvt1', 'tch_pvt2', 'tch_pvt3', 'tch_pvt4', 'tch_pvt5', 'tch_pvt6', 'tch_pvt7', 'tch_pvt9', 'tch_un1', 'tch_un2', 'tch_un3', 'tch_un4', 'tch_un5', 'tch_un6', 'tch_un7', 'tch_un9', 'tch_bs1', 'tch_bs2', 'tch_bs3', 'tch_bs4', 'tch_bs5', 'tch_bs6', 'tch_bs7', 'tch_bs_p', 'tch_s1', 'tch_s2', 'tch_s3', 'tch_s4', 'tch_s5', 'tch_s6', 'tch_s7', 'tch_s_p', 'tch_hs1', 'tch_hs2', 'tch_hs3', 'tch_hs4', 'tch_hs5', 'tch_hs6', 'tch_hs7', 'tch_hs_p', 'tch_grad1', 'tch_grad2', 'tch_grad3', 'tch_grad4', 'tch_grad5', 'tch_grad6', 'tch_grad7', 'tch_grad_p', 'tch_pgrad1', 'tch_pgrad2', 'tch_pgrad3', 'tch_pgrad4', 'tch_pgrad5', 'tch_pgrad6', 'tch_pgrad7', 'tch_pgrad_p', 'tch_mph1', 'tch_mph2', 'tch_mph3', 'tch_mph4', 'tch_mph5', 'tch_mph6', 'tch_mph7', 'tch_mph_p', 'tch_pd1', 'tch_pd2', 'tch_pd3', 'tch_pd4', 'tch_pd5', 'tch_pd6', 'tch_pd7', 'tch_pd_p', 'tch_eduqual_nr1', 'tch_eduqual_nr2', 'tch_eduqual_nr3', 'tch_eduqual_nr4', 'tch_eduqual_nr5', 'tch_eduqual_nr6', 'tch_eduqual_nr7', 'tch_eduqual_nr_p', 'tch_m1', 'tch_m2', 'tch_m3', 'tch_m4', 'tch_m5', 'tch_m6', 'tch_m7', 'tch_f1', 'tch_f2', 'tch_f3', 'tch_f4', 'tch_f5', 'tch_f6', 'tch_f7', 'tch_nr1', 'tch_nr2', 'tch_nr3', 'tch_nr4', 'tch_nr5', 'tch_nr6', 'tch_nr7', 'tch_m_p1', 'tch_m_p2', 'tch_m_p3', 'tch_m_p4', 'tch_m_p5', 'tch_m_p6', 'tch_m_p7', 'tch_f_p1', 'tch_f_p2', 'tch_f_p3', 'tch_f_p4', 'tch_f_p5', 'tch_f_p6', 'tch_f_p7', 'tch_nr_p1', 'tch_nr_p2', 'tch_nr_p3', 'tch_nr_p4', 'tch_nr_p5', 'tch_nr_p6', 'tch_nr_p7', 'tch_sc_m1', 'tch_sc_m2', 'tch_sc_m3', 'tch_sc_m4', 'tch_sc_m5', 'tch_sc_m6', 'tch_sc_m7', 'tch_sc_f1', 'tch_sc_f2', 'tch_sc_f3', 'tch_sc_f4', 'tch_sc_f5', 'tch_sc_f6', 'tch_sc_f7', 'tch_st_m1', 'tch_st_m2', 'tch_st_m3', 'tch_st_m4', 'tch_st_m5', 'tch_st_m6', 'tch_st_m7', 'tch_st_f1', 'tch_st_f2', 'tch_st_f3', 'tch_st_f4', 'tch_st_f5', 'tch_st_f6', 'tch_st_f7', 'trn_tch_m1', 'trn_tch_m2', 'trn_tch_m3', 'trn_tch_m4', 'trn_tch_m5', 'trn_tch_m6', 'trn_tch_m7', 'trn_tch_f1', 'trn_tch_f2', 'trn_tch_f3', 'trn_tch_f4', 'trn_tch_f5', 'trn_tch_f6', 'trn_tch_f7', 'prof_trn_tch_r', 'prof_trn_tch_p', 'days_nontch', 'tch_nontch']

## Exercise 3 - Data Cleaning (3 Marks)

1.  **Overall_lit** is our target variable. Delete rows with missing overall_lit value

   Hint: Refer to the link [dropna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html).


2.  Convert categorical values to numerical values.

  For example, If a feature contains categorical values such as dog, cat, mouse, etc then replace them with 0, 1, 2, etc or use [Sklearn LabelEncoder's](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html)

3. Replace the missing values in any other column appropriately with mean / median / mode.

  Hint: Use pandas [fillna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html) function to replace the missing values

In [ ]:
# YOUR CODE HERE for data cleaning
df_merged.dropna(subset=['overall_lit'], inplace=True)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_merged['overall_lit'].unique()
df_merged['overall_lit_encoded'] = le.fit_transform(df_merged['overall_lit'])
df_merged['overall_lit_encoded'].unique()

for i, category in enumerate(le.classes_):
    print(f"{category}: {i}")

display(df_merged[['overall_lit', 'overall_lit_encoded']].head())
df_merged.info()

High: 0
Low: 1
Medium: 2

                overall_lit  overall_lit_encoded
Unique_ID
2012-13_35_3501        High                    0
2012-13_35_3503        High                    0
2012-13_35_3502        High                    0
2012-13_28_2801         Low                    1
2012-13_28_2822         Low                    1

<class 'pandas.core.frame.DataFrame'>
Index: 1268 entries, 2012-13_35_3501 to 2013-14_19_1904
Columns: 201 entries, year_x to overall_lit_encoded
dtypes: float64(9), int64(185), object(7)
memory usage: 2.0+ MB

In [ ]:
# Identify numerical and categorical columns
numerical_cols = df_merged.select_dtypes(include=np.number).columns
categorical_cols = df_merged.select_dtypes(include='object').columns

# Impute numerical columns with the median
for col in numerical_cols:
    if df_merged[col].isnull().any():
        df_merged[col] = df_merged[col].fillna(df_merged[col].median())

# Impute categorical columns with the mode
for col in categorical_cols:
    if df_merged[col].isnull().any():
        # Mode might return multiple values if there's a tie, so take the first one
        df_merged[col] = df_merged[col].fillna(df_merged[col].mode()[0])

# Verify that there are no more missing values
print("Missing values after imputation:")
display(df_merged.isnull().sum()[df_merged.isnull().sum() > 0])

# Display the head of the DataFrame to show the changes
display(df_merged.head(2))
df_merged.info()

Missing values after imputation:

Series([], dtype: int64)

,year_x,statecd_x,statename_x,distcd_x,distname_x,blocks,clusters,villages,totschools,totpopulation,p_06_pop,p_urb_pop,sexratio,sexratio_06,growthrate,p_sc_pop,p_st_pop,overall_lit,female_lit,statecd_y,statename_y,distcd_y,distname_y,year_y,tch_govt1,tch_govt2,tch_govt3,tch_govt4,tch_govt5,tch_govt6,tch_govt7,tch_govt9,tch_pvt1,tch_pvt2,tch_pvt3,tch_pvt4,tch_pvt5,tch_pvt6,tch_pvt7,tch_pvt9,tch_un1,tch_un2,tch_un3,tch_un4,tch_un5,tch_un6,tch_un7,tch_un9,tch_bs1,tch_bs2,tch_bs3,tch_bs4,tch_bs5,tch_bs6,tch_bs7,tch_bs_p,tch_s1,tch_s2,tch_s3,tch_s4,tch_s5,tch_s6,tch_s7,tch_s_p,tch_hs1,tch_hs2,tch_hs3,tch_hs4,tch_hs5,tch_hs6,tch_hs7,tch_hs_p,tch_grad1,tch_grad2,tch_grad3,tch_grad4,tch_grad5,tch_grad6,tch_grad7,tch_grad_p,tch_pgrad1,tch_pgrad2,tch_pgrad3,tch_pgrad4,tch_pgrad5,tch_pgrad6,tch_pgrad7,tch_pgrad_p,tch_mph1,tch_mph2,tch_mph3,tch_mph4,tch_mph5,tch_mph6,tch_mph7,tch_mph_p,tch_pd1,tch_pd2,tch_pd3,tch_pd4,tch_pd5,tch_pd6,tch_pd7,tch_pd_p,tch_eduqual_nr1,tch_eduqual_nr2,tch_eduqual_nr3,tch_eduqual_nr4,tch_eduqual_nr5,tch_eduqual_nr6,tch_eduqual_nr7,tch_eduqual_nr_p,tch_m1,tch_m2,tch_m3,tch_m4,tch_m5,tch_m6,tch_m7,tch_f1,tch_f2,tch_f3,tch_f4,tch_f5,tch_f6,tch_f7,tch_nr1,tch_nr2,tch_nr3,tch_nr4,tch_nr5,tch_nr6,tch_nr7,tch_m_p1,tch_m_p2,tch_m_p3,tch_m_p4,tch_m_p5,tch_m_p6,tch_m_p7,tch_f_p1,tch_f_p2,tch_f_p3,tch_f_p4,tch_f_p5,tch_f_p6,tch_f_p7,tch_nr_p1,tch_nr_p2,tch_nr_p3,tch_nr_p4,tch_nr_p5,tch_nr_p6,tch_nr_p7,tch_sc_m1,tch_sc_m2,tch_sc_m3,tch_sc_m4,tch_sc_m5,tch_sc_m6,tch_sc_m7,tch_sc_f1,tch_sc_f2,tch_sc_f3,tch_sc_f4,tch_sc_f5,tch_sc_f6,tch_sc_f7,tch_st_m1,tch_st_m2,tch_st_m3,tch_st_m4,tch_st_m5,tch_st_m6,tch_st_m7,tch_st_f1,tch_st_f2,tch_st_f3,tch_st_f4,tch_st_f5,tch_st_f6,tch_st_f7,trn_tch_m1,trn_tch_m2,trn_tch_m3,trn_tch_m4,trn_tch_m5,trn_tch_m6,trn_tch_m7,trn_tch_f1,trn_tch_f2,trn_tch_f3,trn_tch_f4,trn_tch_f5,trn_tch_f6,trn_tch_f7,prof_trn_tch_r,prof_trn_tch_p,days_nontch,tch_nontch,overall_lit_encoded
Unique_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2012-13_35_3501,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3501,ANDAMANS ...,3,16,83,212,237586.0,23616.05,55.89,874.0,980.0,13.97,0.0,1.72,High,84.52,35,ANDAMAN & NICOBAR ISLANDS ...,3501,ANDAMANS ...,2012-13,329,429,1097,0,127,432,0,0,308,117,317,0,0,83,0,0,0,0,0,0,0,0,0,0,15,9,13,0,0,4,0,11,9,10,25,0,2,20,0,5,241,181,244,0,29,160,0,94,138,208,475,0,48,194,0,80,64,114,540,0,43,112,0,57,2,5,72,0,3,8,0,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,116,166,535,0,62,161,0,353,361,835,0,63,337,0,0,0,0,0,0,0,0,19,6,8,0,0,0,0,149,13,36,0,2,17,0,0,0,0,0,0,0,0,0,0,4,0,0,2,0,0,0,1,0,0,0,0,4,3,16,0,0,8,0,11,5,18,0,1,11,0,69,97,64,0,14,66,0,134,176,135,0,22,103,0,2968,228,12,519,0
2012-13_35_3503,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3503,MIDDLE AND NORTH ANDAMANS ...,3,13,76,181,105539.0,11651.51,2.60,925.0,975.0,-0.07,0.0,0.72,High,79.39,35,ANDAMAN & NICOBAR ISLANDS ...,3503,MIDDLE AND NORTH ANDAMANS ...,2012-13,305,285,194,95,268,175,0,0,103,31,0,0,0,15,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,3,7,4,3,2,1,2,0,0,255,110,33,22,6,63,0,37,55,95,56,31,69,66,0,71,22,35,80,29,144,40,0,94,0,3,3,5,17,1,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,177,123,81,56,142,74,0,163,124,94,33,95,99,0,0,0,0,0,0,0,0,19,32,3,1,5,2,0,49,37,16,5,26,15,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,6,2,7,0,0,2,2,3,0,4,2,0,126,79,32,8,45,37,0,84,85,40,3,28,60,0,1249,203,8,362,0

<class 'pandas.core.frame.DataFrame'>
Index: 1268 entries, 2012-13_35_3501 to 2013-14_19_1904
Columns: 201 entries, year_x to overall_lit_encoded
dtypes: float64(9), int64(185), object(7)
memory usage: 2.0+ MB

## Exercise 4 - (3 Marks)

1. Remove the unnecessary columns which are not contributing to the overall literacy rate

2. Verify if there are any duplicate columns and remove them.

  For example: state name and district name are the same as state code and district code.

3. Make sure that the final dataframe has no null or nan values. Delete the rows with missing values.

   Hint: Give df.isna() to verify on the nan values in the dataframe.

In [ ]:
col_to_drop = ['year_y', 'year_x', 'statecd_y', 'statename_y', 'statename_x', 'distcd_y', 'distname_x', 'distname_y', 'overall_lit']
df_merged = df_merged.drop(columns=col_to_drop, errors='ignore')

display(df_merged.info())
df_merged.isna().sum()[df_merged.isna().sum() > 0]
print(df_merged.dtypes.unique())
pd.set_option('display.max_columns', None)
df_merged.head()

<class 'pandas.core.frame.DataFrame'>
Index: 1268 entries, 2012-13_35_3501 to 2013-14_19_1904
Columns: 192 entries, statecd_x to overall_lit_encoded
dtypes: float64(9), int64(183)
memory usage: 1.9+ MB

None

[dtype('int64') dtype('float64')]

,statecd_x,distcd_x,blocks,clusters,villages,totschools,totpopulation,p_06_pop,p_urb_pop,sexratio,sexratio_06,growthrate,p_sc_pop,p_st_pop,female_lit,tch_govt1,tch_govt2,tch_govt3,tch_govt4,tch_govt5,tch_govt6,tch_govt7,tch_govt9,tch_pvt1,tch_pvt2,tch_pvt3,tch_pvt4,tch_pvt5,tch_pvt6,tch_pvt7,tch_pvt9,tch_un1,tch_un2,tch_un3,tch_un4,tch_un5,tch_un6,tch_un7,tch_un9,tch_bs1,tch_bs2,tch_bs3,tch_bs4,tch_bs5,tch_bs6,tch_bs7,tch_bs_p,tch_s1,tch_s2,tch_s3,tch_s4,tch_s5,tch_s6,tch_s7,tch_s_p,tch_hs1,tch_hs2,tch_hs3,tch_hs4,tch_hs5,tch_hs6,tch_hs7,tch_hs_p,tch_grad1,tch_grad2,tch_grad3,tch_grad4,tch_grad5,tch_grad6,tch_grad7,tch_grad_p,tch_pgrad1,tch_pgrad2,tch_pgrad3,tch_pgrad4,tch_pgrad5,tch_pgrad6,tch_pgrad7,tch_pgrad_p,tch_mph1,tch_mph2,tch_mph3,tch_mph4,tch_mph5,tch_mph6,tch_mph7,tch_mph_p,tch_pd1,tch_pd2,tch_pd3,tch_pd4,tch_pd5,tch_pd6,tch_pd7,tch_pd_p,tch_eduqual_nr1,tch_eduqual_nr2,tch_eduqual_nr3,tch_eduqual_nr4,tch_eduqual_nr5,tch_eduqual_nr6,tch_eduqual_nr7,tch_eduqual_nr_p,tch_m1,tch_m2,tch_m3,tch_m4,tch_m5,tch_m6,tch_m7,tch_f1,tch_f2,tch_f3,tch_f4,tch_f5,tch_f6,tch_f7,tch_nr1,tch_nr2,tch_nr3,tch_nr4,tch_nr5,tch_nr6,tch_nr7,tch_m_p1,tch_m_p2,tch_m_p3,tch_m_p4,tch_m_p5,tch_m_p6,tch_m_p7,tch_f_p1,tch_f_p2,tch_f_p3,tch_f_p4,tch_f_p5,tch_f_p6,tch_f_p7,tch_nr_p1,tch_nr_p2,tch_nr_p3,tch_nr_p4,tch_nr_p5,tch_nr_p6,tch_nr_p7,tch_sc_m1,tch_sc_m2,tch_sc_m3,tch_sc_m4,tch_sc_m5,tch_sc_m6,tch_sc_m7,tch_sc_f1,tch_sc_f2,tch_sc_f3,tch_sc_f4,tch_sc_f5,tch_sc_f6,tch_sc_f7,tch_st_m1,tch_st_m2,tch_st_m3,tch_st_m4,tch_st_m5,tch_st_m6,tch_st_m7,tch_st_f1,tch_st_f2,tch_st_f3,tch_st_f4,tch_st_f5,tch_st_f6,tch_st_f7,trn_tch_m1,trn_tch_m2,trn_tch_m3,trn_tch_m4,trn_tch_m5,trn_tch_m6,trn_tch_m7,trn_tch_f1,trn_tch_f2,trn_tch_f3,trn_tch_f4,trn_tch_f5,trn_tch_f6,trn_tch_f7,prof_trn_tch_r,prof_trn_tch_p,days_nontch,tch_nontch,overall_lit_encoded
Unique_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2012-13_35_3501,35,3501,3,16,83,212,237586.0,23616.05,55.89,874.0,980.0,13.97,0.00,1.72,84.52,329,429,1097,0,127,432,0,0,308,117,317,0,0,83,0,0,0,0,0,0,0,0,0,0,15,9,13,0,0,4,0,11,9,10,25,0,2,20,0,5,241,181,244,0,29,160,0,94,138,208,475,0,48,194,0,80,64,114,540,0,43,112,0,57,2,5,72,0,3,8,0,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,116,166,535,0,62,161,0,353,361,835,0,63,337,0,0,0,0,0,0,0,0,19,6,8,0,0,0,0,149,13,36,0,2,17,0,0,0,0,0,0,0,0,0,0,4,0,0,2,0,0,0,1,0,0,0,0,4,3,16,0,0,8,0,11,5,18,0,1,11,0,69,97,64,0,14,66,0,134,176,135,0,22,103,0,2968,228,12,519,0
2012-13_35_3503,35,3503,3,13,76,181,105539.0,11651.51,2.60,925.0,975.0,-0.07,0.00,0.72,79.39,305,285,194,95,268,175,0,0,103,31,0,0,0,15,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,3,7,4,3,2,1,2,0,0,255,110,33,22,6,63,0,37,55,95,56,31,69,66,0,71,22,35,80,29,144,40,0,94,0,3,3,5,17,1,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,177,123,81,56,142,74,0,163,124,94,33,95,99,0,0,0,0,0,0,0,0,19,32,3,1,5,2,0,49,37,16,5,26,15,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,6,2,7,0,0,2,2,3,0,4,2,0,126,79,32,8,45,37,0,84,85,40,3,28,60,0,1249,203,8,362,0
2012-13_35_3502,35,3502,3,8,42,58,36819.0,4226.82,0.00,778.0,961.0,-12.48,0.00,64.28,70.70,110,95,56,0,135,114,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,26,7,8,0,3,10,0,0,72,29,7,0,2,34,0,8,7,36,13,0,34,41,0,26,3,7,14,0,60,6,0,45,0,1,4,0,7,4,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,42,35,28,0,65,42,0,67,45,19,0,41,53,0,0,0,0,0,0,0,0,1,10,3,0,12,3,0,8,5,6,0,17,16,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,33,29,18,0,27,27,0,53,32,16,0,28,40,0,36,25,18,0,22,31,0,58,29,23,0,17,46,0,430,78,20,28,0
2012-13_28_2801,28,2801,52,356,1576,4983,2737738.0,295675.70,27.68,1003.0,942.0,10.04,17.82,18.09,51.99,4749,1788,38,0,22,939,4309,0,2004,2298,0,0,0,327,2222,0,214,82,0,0,0,5,5,0,0,0,0,0,0,0,0,0,798,152,0,0,0,52,51,69,1641,672,0,0,0,80,269,141,3225,2324,0,0,6,456,3006,525,1015,866,12,0,13,361,2816,328,25,26,0,0,3,11,56,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4070,2300,10,0,16,624,4457,2634,1740,2,0,6,336,1741,0,0,0,0,0,0,0,131,70,6,0,0,171,42,132,58,20,0,0,140,296,0,0,0,0,0,0,0,559,387,5,0,2,58,621,401,252,4,0,0,37,294,1447,394,1,0,1,409,260,288,126,1,0,0,187,146,1964,554,0,0,0,46,641,830,267,0,0,0,8,248,16419,845,13,263,1
2012-13_28_2822,28,2822,63,564,929,5188,4083315.0,427114.75,28.09,977.0,927.0,12.16,14.29,3.78,54.31,5797,2879,209,8,6733,2,52,0,2063,2184,106,0,2307,0,41,0,52,97,0,0,8,0,0,0,0,0,0,0,0,0,0,0,132,80,1,0,69,0,6,12,932,385,4,0,229,0,19,67,4315,2980,87,5,3910,2,38,426,2267,1584,193,3,4413,0,23,189,31,37,7,0,90,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4179,3022,150,7,5580,1,37,3498,2044,142,1,3131,1,33,0,0,0,0,0,0,16,150,58,4,0,15,0,0,85,36,19,0,322,0,7,0,0,0,0,0,0,0,528,291,15,0,591,0,1,457,236,12,0,444,1,4,281,143,5,0,210,0,3,136,69,3,0,139,0,0,2521,1161,2,0,1226,0,10,1652,726,0,0,591,0,3,21487,676,14,1185,1

## Exercise 5 - Apply Correlation Matrix (2 Marks)

Correlation is a statistical technique that can show whether and how strongly pairs of variables are related. More number of features does not imply better accuracy. More features may lead to a decline in the accuracy and create noise in the model, if they contain any irrelevant features.

*Features with high correlation value will imply the same meaning. Hence removing the highly correlated features*

**Function Description:**

`remove_Highly_Correlated()` function removes highly correlated features in the dataframe.
- Creates a correlation matrix of row and column wise features
- Extracts only uppertriangular matrix as correlation matrix, which will have the same values below and above the diagonal
- Removes columns which are having correlation value more than the threshold value.

In [ ]:
def remove_Highly_Correlated(df, bar=0.9):
  # Select only numerical columns for correlation calculation
  numerical_df = df.select_dtypes(include=np.number)

  # Creates correlation matrix
  corr = numerical_df.corr()

 # Set Up Mask To Hide Upper Triangle
  mask = np.triu(np.ones_like(corr, dtype=bool))
  tri_df = corr.mask(mask)

  # Finding features with correlation value more than specified threshold value (bar=0.9)
  highly_cor_col = [col for col in tri_df.columns if any(tri_df[col] > bar )]
  print("length of highly correlated columns",len(highly_cor_col))

  # Drop the highly correlated columns
  reduced_df = df.drop(highly_cor_col, axis = 1)
  print("shape of data",df.shape,"shape of reduced data",reduced_df.shape)
  return reduced_df

In [ ]:
df_merged = remove_Highly_Correlated(df_merged)

print("DataFrame info after removing highly correlated features:")
display(df_merged.info())

length of highly correlated columns 26
shape of data (1268, 192) shape of reduced data (1268, 166)
DataFrame info after removing highly correlated features:
<class 'pandas.core.frame.DataFrame'>
Index: 1268 entries, 2012-13_35_3501 to 2013-14_19_1904
Columns: 166 entries, distcd_x to overall_lit_encoded
dtypes: float64(8), int64(158)
memory usage: 1.6+ MB

None

## Exercise 6 - (3 Marks)

Perform Standard Scaling on the data feature/column wise.

**Hint:** In order to understand the idea behind the terms used above, you may refer to the following link:

[StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)

In [ ]:
# YOUR CODE HERE
# Identify numerical columns for scaling (excluding the target variable if present)
# The 'overall_lit_encoded' is our target variable, so we exclude it from scaling.
# Also exclude any non-numeric columns like 'statename_x', 'distname_x', 'year_y'

numerical_cols_for_scaling = df_merged.select_dtypes(include=np.number).columns.tolist()
if 'overall_lit_encoded' in numerical_cols_for_scaling:
    numerical_cols_for_scaling.remove('overall_lit_encoded')


from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Apply StandardScaler to the selected numerical columns
df_merged[numerical_cols_for_scaling] = scaler.fit_transform(df_merged[numerical_cols_for_scaling])

print("DataFrame head after Standard Scaling:")
display(df_merged.head())

print("Info of DataFrame after Standard Scaling:")
display(df_merged.info())

DataFrame head after Standard Scaling:

,distcd_x,blocks,clusters,villages,totschools,p_06_pop,p_urb_pop,sexratio,sexratio_06,growthrate,p_sc_pop,p_st_pop,female_lit,tch_govt2,tch_govt3,tch_govt6,tch_govt9,tch_pvt1,tch_pvt2,tch_pvt4,tch_pvt5,tch_pvt9,tch_un1,tch_un2,tch_un3,tch_un4,tch_un5,tch_un6,tch_un7,tch_un9,tch_bs1,tch_bs2,tch_bs3,tch_bs4,tch_bs5,tch_bs6,tch_bs7,tch_bs_p,tch_s1,tch_s2,tch_s3,tch_s4,tch_s5,tch_s6,tch_s_p,tch_hs1,tch_hs2,tch_hs3,tch_hs4,tch_hs5,tch_hs6,tch_hs7,tch_hs_p,tch_grad1,tch_grad2,tch_grad_p,tch_pgrad1,tch_pgrad2,tch_pgrad4,tch_pgrad6,tch_pgrad_p,tch_mph1,tch_mph2,tch_mph4,tch_mph5,tch_mph6,tch_mph7,tch_mph_p,tch_pd1,tch_pd2,tch_pd3,tch_pd4,tch_pd5,tch_pd6,tch_pd7,tch_pd_p,tch_eduqual_nr1,tch_eduqual_nr2,tch_eduqual_nr3,tch_eduqual_nr4,tch_eduqual_nr5,tch_eduqual_nr6,tch_eduqual_nr7,tch_eduqual_nr_p,tch_m1,tch_m4,tch_f1,tch_f2,tch_f3,tch_f4,tch_f5,tch_f6,tch_f7,tch_nr1,tch_nr2,tch_nr3,tch_nr4,tch_nr5,tch_nr6,tch_nr7,tch_m_p1,tch_m_p2,tch_m_p3,tch_m_p6,tch_m_p7,tch_f_p1,tch_f_p2,tch_f_p3,tch_f_p4,tch_f_p5,tch_f_p6,tch_f_p7,tch_nr_p1,tch_nr_p2,tch_nr_p3,tch_nr_p4,tch_nr_p5,tch_nr_p6,tch_nr_p7,tch_sc_m1,tch_sc_m2,tch_sc_m3,tch_sc_m4,tch_sc_m5,tch_sc_m6,tch_sc_m7,tch_sc_f1,tch_sc_f2,tch_sc_f3,tch_sc_f4,tch_sc_f5,tch_sc_f6,tch_sc_f7,tch_st_m1,tch_st_m2,tch_st_m3,tch_st_m4,tch_st_m5,tch_st_m6,tch_st_m7,tch_st_f1,tch_st_f2,tch_st_f3,tch_st_f4,tch_st_f5,tch_st_f6,tch_st_f7,trn_tch_m1,trn_tch_m2,trn_tch_m3,trn_tch_m4,trn_tch_m5,trn_tch_m6,trn_tch_m7,trn_tch_f1,trn_tch_f2,trn_tch_f3,trn_tch_f4,trn_tch_f5,trn_tch_f6,trn_tch_f7,prof_trn_tch_r,prof_trn_tch_p,days_nontch,tch_nontch,overall_lit_encoded
Unique_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2012-13_35_3501,1.894217,-0.828445,-1.109180,-1.307226,-1.375512,-1.139319,1.633453,-1.101203,1.386624,-0.322648,-1.637575,-0.587946,1.592947,-0.563060,1.982636,0.917437,-0.057653,-0.465004,-0.691785,-0.432789,-0.449822,-0.070194,-0.443790,-0.408914,-0.192014,-0.177828,-0.161116,-0.212356,-0.295949,-0.045741,-0.541015,-0.335549,0.006453,-0.347761,-0.495357,-0.092507,-0.388781,-0.075883,-0.581490,-0.508036,-0.153006,-0.500894,-0.435084,-0.230614,-0.389613,-0.870330,-0.578284,0.991427,-0.430667,-0.295685,0.484013,-0.416319,-0.328468,-0.854292,-0.713725,-0.475232,-0.799003,-0.577227,-0.599651,-0.160869,-0.389187,-0.629559,-0.312969,-0.573602,-0.311079,0.055676,-0.432545,-0.219688,-0.363713,-0.329612,0.311167,-0.277519,-0.235602,-0.227151,-0.20909,-0.256719,-0.123913,-0.166116,-0.102395,-0.074254,-0.073011,-0.121191,-0.113252,-0.085015,-1.007574,-0.650195,-0.810769,-0.613824,0.142369,-0.685292,-0.438269,0.036222,-0.350705,-0.213126,-0.175638,-0.113562,-0.139723,-0.14038,-0.148428,-0.153516,-0.489239,-0.280579,-0.064108,-0.361410,-0.333313,-0.184154,-0.349373,0.141133,-0.308761,-0.225174,0.039795,-0.266459,-0.08562,-0.062919,-0.048698,-0.059102,-0.045907,0.0,-0.037704,-0.805912,-0.717708,-0.428138,-0.594006,-0.472464,-0.393978,-0.452962,-0.799027,-0.756515,-0.427923,-0.573238,-0.422832,-0.481144,-0.341971,-0.670298,-0.569430,0.000019,-0.356009,-0.447754,-0.306048,-0.456980,-0.529933,-0.498049,0.022880,-0.292049,-0.411878,-0.201113,-0.388726,-0.613726,-0.444931,0.464594,-0.518477,-0.347137,1.058771,-0.388470,-0.547462,-0.292820,0.514248,-0.494098,-0.292423,1.274906,-0.377127,-0.785267,-0.293687,-0.359209,0.047086,0
2012-13_35_3503,1.896343,-0.828445,-1.138707,-1.318262,-1.396885,-1.199237,-1.165845,-0.283457,1.273292,-1.561064,-1.637575,-0.625210,1.182316,-0.623661,0.082006,0.052255,-0.057653,-0.626401,-0.753294,-0.432789,-0.449822,-0.070194,-0.443790,-0.408914,-0.192014,-0.177828,-0.161116,-0.212356,-0.295949,-0.045741,-0.636348,-0.389045,-0.364172,-0.347761,-0.495357,-0.132265,-0.388781,-0.376454,-0.583698,-0.515599,-0.494167,-0.476705,-0.444052,-0.534408,-0.430887,-0.854825,-0.648857,-0.350383,-0.367344,-0.437124,-0.203293,-0.416319,-0.486911,-0.916319,-0.808946,-0.489918,-0.855857,-0.697373,-0.533987,-0.422701,-0.228643,-0.687386,-0.345729,-0.117254,-0.234242,-0.287981,-0.432545,-0.019354,-0.363713,-0.329612,-0.332487,-0.277519,-0.235602,-0.227151,-0.20909,-0.256719,-0.123913,-0.166116,-0.102395,-0.074254,-0.073011,-0.121191,-0.113252,-0.085015,-0.973737,-0.582401,-0.926697,-0.756276,-0.408105,-0.594897,-0.406783,-0.374824,-0.350705,-0.213126,-0.175638,-0.113562,-0.139723,-0.14038,-0.148428,-0.153516,-0.489239,-0.188201,-0.213757,-0.311081,-0.333313,-0.393470,-0.142752,-0.067563,-0.216407,-0.040972,-0.003278,-0.266459,-0.08562,-0.062919,-0.048698,-0.059102,-0.045907,0.0,-0.037704,-0.805912,-0.714121,-0.482751,-0.594006,-0.472464,-0.419625,-0.452962,-0.795681,-0.751285,-0.438048,-0.573238,-0.422832,-0.481144,-0.341971,-0.680049,-0.577239,-0.245599,-0.345422,-0.351120,-0.413468,-0.456980,-0.561445,-0.513462,-0.309062,-0.292049,-0.334555,-0.356628,-0.388726,-0.557294,-0.466123,0.148773,-0.483692,-0.225009,0.383259,-0.388470,-0.610218,-0.395004,0.038853,-0.470878,-0.264741,0.625907,-0.377127,-1.026722,-0.329009,-0.618519,-0.089579,0
2012-13_35_3502,1.895280,-0.828445,-1.187918,-1.371868,-1.481690,-1.236420,-1.302421,-2.640491,0.955961,-2.655703,-1.637575,1.743320,0.486725,-0.703621,-0.208456,-0.153100,-0.057653,-0.701194,-0.775465,-0.432789,-0.449822,-0.070194,-0.443790,-0.408914,-0.192014,-0.177828,-0.161116,-0.212356,-0.295949,-0.045741,-0.636348,-0.389045,-0.335662,-0.347761,-0.495357,-0.145518,-0.388781,-0.489169,-0.562723,-0.511817,-0.416630,-0.500894,-0.426116,-0.399388,-0.430887,-1.057498,-0.729371,-0.515724,-0.430667,-0.461722,-0.408776,-0.416319,-0.567522,-0.952190,-0.858663,-0.563347,-0.881577,-0.739957,-0.599651,-0.546344,-0.441255,-0.687386,-0.378488,-0.573602,-0.289125,-0.140700,-0.432545,-0.319855,-0.363713,-0.329612,-0.332487,-0.277519,-0.235602,-0.227151,-0.20909,-0.256719,-0.123913,-0.166116,-0.102395,-0.074254,-0.073011,-0.121191,-0.113252,-0.085015,-1.048622,-0.650195,-0.985272,-0.803759,-0.463821,-0.685292,-0.459915,-0.454270,-0.350705,-0.213126,-0.175638,-0.113562,-0.139723,-0.14038,-0.148428,-0.153516,-0.529044,-0.266367,-0.213757,-0.285917,-0.333313,-0.479290,-0.418247,-0.171911,-0.308761,-0.110048,0.018258,-0.266459,-0.08562,-0.062919,-0.048698,-0.059102,-0.045907,0.0,-0.037704,-0.805912,-0.714121,-0.482751,-0.594006,-0.472464,-0.419625,-0.452962,-0.799027,-0.756515,-0.438048,-0.573238,-0.422832,-0.481144,-0.341971,-0.599604,-0.467913,0.049143,-0.356009,-0.075023,-0.050925,-0.456980,-0.382875,-0.359327,-0.021379,-0.292049,0.284023,0.299993,-0.388726,-0.646397,-0.529699,0.010601,-0.518477,-0.315620,0.243498,-0.388470,-0.642850,-0.457886,-0.046217,-0.494098,-0.315492,0.414605,-0.377127,-1.141760,-0.505620,0.159410,-0.380319,0
2012-13_28_2801,1.149962,4.173296,2.237191,1.046709,1.913955,0.223144,0.151596,0.967214,0.525298,-0.669299,0.329059,0.022074,-1.010916,0.008863,-0.246342,2.624236,-0.057653,0.870256,0.868097,-0.432789,-0.449822,-0.070194,0.366912,-0.105111,-0.192014,-0.177828,-0.161116,-0.175711,-0.121505,-0.045741,-0.643157,-0.389045,-0.364172,-0.347761,-0.495357,-0.145518,-0.388781,-0.489169,0.289546,-0.329042,-0.540689,-0.500894,-0.453020,0.309464,0.138690,0.680169,-0.090232,-0.560239,-0.430667,-0.474021,-0.082837,1.560036,-0.197822,1.452660,1.069353,0.250903,0.488336,0.566449,-0.599651,0.744634,0.786685,0.035458,0.031002,-0.573602,-0.311079,0.202958,2.503519,-0.219688,-0.363713,-0.329612,-0.332487,-0.277519,-0.235602,-0.227151,-0.20909,-0.256719,-0.123913,-0.166116,-0.102395,-0.074254,-0.073011,-0.121191,-0.113252,-0.085015,1.185723,-0.650195,0.580984,0.215040,-0.476450,-0.685292,-0.494352,0.034495,1.990157,-0.213126,-0.175638,-0.113562,-0.139723,-0.14038,-0.148428,-0.153516,-0.241562,-0.053188,-0.123968,3.941689,0.802892,-0.219738,0.038042,-0.025824,-0.308761,-0.240524,2.688761,4.815327,-0.08562,-0.062919,-0.048698,-0.059102,-0.045907,0.0,-0.037704,0.493953,0.670290,-0.414485,-0.594006,-0.464287,0.324137,4.369182,0.542591,0.561475,-0.397548,-0.573238,-0.422832,0.284366,2.907276,2.847363,0.957242,-0.368408,-0.356009,-0.433949,5.078390,3.244034,0.439952,0.123628,-0.353321,-0.292049,-0.437652,2.840082,3.267240,1.262384,0.093112,-0.167049,-0.518477,-0.402291,0.592901,3.092836,0.326089,-0.190636,-0.161313,-0.494098,-0.393926,-0.158929,1.903111,1.104093,0.578065,-0.294382,-0.175757,1
2012-13_28_2822,1.172289,5.296136,4.284383,0.026618,2.055296,0.881386,0.173133,0.550323,0.185300,-0.482302,-0.060516,-0.511181,-0.825212,0.468001,0.113578,-0.530144,-0.057653,0.916707,0.786562,-0.432789,1.596410,-0.070194,-0.246797,-0.049537,-0.192014,-0.177828,-0.061265,-0.212356,-0.295949,-0.045741,-0.643157,-0.389045,-0.364172,-0.347761,-0.495357,-0.145518,-0.388781,-0.489169,-0.445701,-0.419800,-0.525181,-0.500894,0.165764,-0.568163,-0.331830,-0.105048,-0.375509,-0.534802,-0.430667,0.934215,-0.649688,-0.276725,-0.403520,2.267230,1.622140,0.089358,2.183130,1.658415,-0.592858,-0.568163,0.183563,0.208941,0.211178,-0.573602,0.166408,-0.337075,-0.432545,-0.319855,-0.363713,-0.329612,-0.332487,-0.277519,-0.235602,-0.227151,-0.20909,-0.256719,-0.123913,-0.166116,-0.102395,-0.074254,-0.073011,-0.121191,-0.113252,-0.085015,1.246186,-0.641720,1.108153,0.397763,-0.372447,-0.682553,2.580407,-0.544078,-0.306335,-0.213126,-0.175638,-0.113562,-0.139723,-0.14038,-0.148428,1.225203,-0.199546,-0.095824,-0.183827,-0.361410,-0.333313,-0.318116,-0.151361,-0.036259,-0.308761,2.230854,-0.326323,-0.146282,-0.08562,-0.062919,-0.048698,-0.059102,-0.045907,0.0,-0.037704,0.421868,0.325981,-0.277953,-0.594006,1.943725,-0.419625,-0.445197,0.729949,0.477793,-0.316548,-0.573238,2.412664,-0.460455,-0.297764,0.004956,-0.022796,-0.270161,-0.356009,2.451266,-0.413468,-0.414276,-0.092259,-0.169228,-0.309062,-0.292049,3.144950,-0.391188,-0.388726,1.813832,0.807754,-0.147310,-0.518477,4.427679,-0.478601,-0.334160,1.357784,0.324775,-0.161313,-0.494098,2.332798,-0.279673,-0.349544,1.815956,0.339287,-0.229554,0.626826,1

Info of DataFrame after Standard Scaling:
<class 'pandas.core.frame.DataFrame'>
Index: 1268 entries, 2012-13_35_3501 to 2013-14_19_1904
Columns: 166 entries, distcd_x to overall_lit_encoded
dtypes: float64(165), int64(1)
memory usage: 1.6+ MB

None

## Exercise 7 - (3 Marks)

Apply different classifiers on the preprocessed data and figure out which classifier gives the best result.

* Split the data into train and test

* Fit the model with train data and find the accuracy of test data

### Expected Accuracy is above 90%

In [ ]:
# YOUR CODE HERE for applying different classifiers

from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df_merged.drop(columns=['overall_lit_encoded'])
y = df_merged['overall_lit_encoded']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of X_train: (1014, 165)
Shape of X_test: (254, 165)
Shape of y_train: (1014,)
Shape of y_test: (254,)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Initialize and train the Logistic Regression model
log_reg_model = LogisticRegression(max_iter=1000, random_state=42)
log_reg_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_log_reg = log_reg_model.predict(X_test)

# Evaluate the model
accuracy_log_reg = accuracy_score(y_test, y_pred_log_reg)
print(f"Logistic Regression Accuracy: {accuracy_log_reg:.4f}")
print("\nLogistic Regression Classification Report:")
print(classification_report(y_test, y_pred_log_reg))

Logistic Regression Accuracy: 0.9016

Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.94      0.93       108
           1       0.94      0.87      0.90        52
           2       0.86      0.88      0.87        94

    accuracy                           0.90       254
   macro avg       0.91      0.89      0.90       254
weighted avg       0.90      0.90      0.90       254

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Initialize and train the Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_rf = rf_model.predict(X_test)

# Evaluate the model
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Random Forest Classifier Accuracy: {accuracy_rf:.4f}")
print("\nRandom Forest Classifier Classification Report:")
print(classification_report(y_test, y_pred_rf))

Random Forest Classifier Accuracy: 0.9646

Random Forest Classifier Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       108
           1       0.94      0.92      0.93        52
           2       0.95      0.96      0.95        94

    accuracy                           0.96       254
   macro avg       0.96      0.96      0.96       254
weighted avg       0.96      0.96      0.96       254

### K-Nearest Neighbors (KNN) Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Initialize and train the KNN model
# Choosing n_neighbors, for example, 5. This can be tuned later.
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_knn = knn_model.predict(X_test)

# Evaluate the model
accuracy_knn = accuracy_score(y_test, y_pred_knn)
print(f"K-Nearest Neighbors Classifier Accuracy: {accuracy_knn:.4f}")
print("\nK-Nearest Neighbors Classification Report:")
print(classification_report(y_test, y_pred_knn))

K-Nearest Neighbors Classifier Accuracy: 0.7205

K-Nearest Neighbors Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.81      0.80       108
           1       0.67      0.69      0.68        52
           2       0.66      0.63      0.64        94

    accuracy                           0.72       254
   macro avg       0.71      0.71      0.71       254
weighted avg       0.72      0.72      0.72       254

### Support Vector Machine (SVM) Classifier

In [ ]:
from sklearn.svm import SVC

# Initialize and train the SVM model
# Using a linear kernel for simplicity. This can be tuned later.
svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_svm = svm_model.predict(X_test)

# Evaluate the model
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f"Support Vector Machine Classifier Accuracy: {accuracy_svm:.4f}")
print("\nSupport Vector Machine Classification Report:")
print(classification_report(y_test, y_pred_svm))

Support Vector Machine Classifier Accuracy: 0.9173

Support Vector Machine Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       108
           1       0.92      0.94      0.93        52
           2       0.89      0.88      0.89        94

    accuracy                           0.92       254
   macro avg       0.92      0.92      0.92       254
weighted avg       0.92      0.92      0.92       254

### Predicting Literacy Rate for a District using Random Forest

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier

# --- Re-load initial raw dataframes (without any dropping yet) ---
df1_raw = pd.read_csv('/content/Districtwise_Basicdata.csv', skiprows=1, header=0)
df1_raw.columns = df1_raw.columns.str.strip().str.lower()

df2_raw = pd.read_csv('/content/Districtwise_Teacher_indicator.csv', skiprows=3, header=0)
df2_raw = df2_raw.rename(columns={"ac_year": "year"})
df2_raw.columns = df2_raw.columns.str.strip().str.lower()

df1_raw['Unique_ID'] = df1_raw['year'].astype(str) + '_' + df1_raw['statecd'].astype(str) + '_' + df1_raw['distcd'].astype(str)
df2_raw['Unique_ID'] = df2_raw['year'].astype(str) + '_' + df2_raw['statecd'].astype(str) + '_' + df2_raw['distcd'].astype(str)

df1_raw.set_index('Unique_ID', inplace=True)
df2_raw.set_index('Unique_ID', inplace=True)

# Create a raw merged dataframe to look up districts, without dropping based on 'overall_lit'
df_raw_merged = pd.merge(df1_raw, df2_raw, left_index=True, right_index=True, how='inner')

In [ ]:
def predict_literacy_for_district(district_name):
    """
    Predicts the literacy rate (High, Medium, Low) for a given district name.
    Applies the full preprocessing pipeline used for training.
    """
    # 1. Find rows in df_raw_merged matching the district name
    # Use str.contains for partial matching and case-insensitivity
    district_rows_raw = df_raw_merged[df_raw_merged['distname_x'].str.contains(district_name, case=False, na=False)].copy()

    if district_rows_raw.empty:
        print(f"District '{district_name}' not found in the dataset.")
        return

    print(f"Found {len(district_rows_raw)} entries for '{district_name}'. Predicting for each entry:")

    # 2. Apply the same column drops as done for the training data
    district_data_processed = district_rows_raw.drop(columns=col_to_drop, errors='ignore')

    # 3. Ensure all required feature columns are present and in the correct order as X (training data)
    training_feature_columns = X.columns.tolist()

    # Drop any columns in district_data_processed that are not in training_feature_columns
    extra_cols = [col for col in district_data_processed.columns if col not in training_feature_columns]
    district_data_processed.drop(columns=extra_cols, inplace=True)

    # Add any missing columns that were in training_feature_columns but not in district_data_processed
    missing_cols_in_input = set(training_feature_columns) - set(district_data_processed.columns)
    for c in missing_cols_in_input:
        district_data_processed[c] = np.nan # Fill with NaN, which will be imputed later

    # Reorder columns to match X.columns
    district_data_final = district_data_processed[training_feature_columns]

    # 4. Impute missing numerical values using the stored medians from the training data
    numerical_cols_to_impute = district_data_final.select_dtypes(include=np.number).columns
    for col in numerical_cols_to_impute:
        if col in median_imputation_values:
            district_data_final[col] = district_data_final[col].fillna(median_imputation_values[col])

    # 5. Scale the numerical features using the *fitted* scaler
    cols_to_scale = [col for col in training_feature_columns if col in district_data_final.select_dtypes(include=np.number).columns]
    district_data_final[cols_to_scale] = scaler.transform(district_data_final[cols_to_scale])

    # 6. Make predictions using the Random Forest model
    predictions_encoded = rf_model.predict(district_data_final)
    predictions_proba = rf_model.predict_proba(district_data_final)

    # 7. Inverse transform to get original labels
    predictions_label = le.inverse_transform(predictions_encoded)

    # 8. Find confidence for the predicted class
    confidence = np.max(predictions_proba, axis=1)

    results = []
    for i in range(len(district_rows_raw)):
        unique_id = district_rows_raw.index[i]
        predicted_class_index = predictions_encoded[i]
        # Get the probability for the predicted class only
        confidence_for_predicted_class = predictions_proba[i, predicted_class_index]
        result_str = f"  - Unique ID: {unique_id}, Predicted Literacy: {predictions_label[i]} (Confidence: {confidence_for_predicted_class*100:.2f}%)"
        results.append(result_str)
    print("\n".join(results))

    print(f"\nRandom Forest Classifier (used for prediction) Accuracy on training data: {accuracy_rf*100:.2f}%")

In [ ]:
print("Raw data for Koraput from df_raw_merged (before preprocessing):")
koraput_raw_data = df_raw_merged[df_raw_merged['distname_x'].str.contains('Koraput', case=False, na=False)].copy()
display(koraput_raw_data[['distname_x', 'overall_lit']].drop_duplicates())
display(koraput_raw_data.head())

Raw data for Koraput from df_raw_merged (before preprocessing):

                                                        distname_x overall_lit
Unique_ID
2012-13_21_2129  KORAPUT                                       ...         Low

,year_x,statecd_x,statename_x,distcd_x,distname_x,blocks,clusters,villages,totschools,totpopulation,p_06_pop,p_urb_pop,sexratio,sexratio_06,growthrate,p_sc_pop,p_st_pop,overall_lit,female_lit,statecd_y,statename_y,distcd_y,distname_y,year_y,tch_govt1,tch_govt2,tch_govt3,tch_govt4,tch_govt5,tch_govt6,tch_govt7,tch_govt9,tch_pvt1,tch_pvt2,tch_pvt3,tch_pvt4,tch_pvt5,tch_pvt6,tch_pvt7,tch_pvt9,tch_un1,tch_un2,tch_un3,tch_un4,tch_un5,tch_un6,tch_un7,tch_un9,tch_bs1,tch_bs2,tch_bs3,tch_bs4,tch_bs5,tch_bs6,tch_bs7,tch_bs_p,tch_s1,tch_s2,tch_s3,tch_s4,tch_s5,tch_s6,tch_s7,tch_s_p,tch_hs1,tch_hs2,tch_hs3,tch_hs4,tch_hs5,tch_hs6,tch_hs7,tch_hs_p,tch_grad1,tch_grad2,tch_grad3,tch_grad4,tch_grad5,tch_grad6,tch_grad7,tch_grad_p,tch_pgrad1,tch_pgrad2,tch_pgrad3,tch_pgrad4,tch_pgrad5,tch_pgrad6,tch_pgrad7,tch_pgrad_p,tch_mph1,tch_mph2,tch_mph3,tch_mph4,tch_mph5,tch_mph6,tch_mph7,tch_mph_p,tch_pd1,tch_pd2,tch_pd3,tch_pd4,tch_pd5,tch_pd6,tch_pd7,tch_pd_p,tch_eduqual_nr1,tch_eduqual_nr2,tch_eduqual_nr3,tch_eduqual_nr4,tch_eduqual_nr5,tch_eduqual_nr6,tch_eduqual_nr7,tch_eduqual_nr_p,tch_m1,tch_m2,tch_m3,tch_m4,tch_m5,tch_m6,tch_m7,tch_f1,tch_f2,tch_f3,tch_f4,tch_f5,tch_f6,tch_f7,tch_nr1,tch_nr2,tch_nr3,tch_nr4,tch_nr5,tch_nr6,tch_nr7,tch_m_p1,tch_m_p2,tch_m_p3,tch_m_p4,tch_m_p5,tch_m_p6,tch_m_p7,tch_f_p1,tch_f_p2,tch_f_p3,tch_f_p4,tch_f_p5,tch_f_p6,tch_f_p7,tch_nr_p1,tch_nr_p2,tch_nr_p3,tch_nr_p4,tch_nr_p5,tch_nr_p6,tch_nr_p7,tch_sc_m1,tch_sc_m2,tch_sc_m3,tch_sc_m4,tch_sc_m5,tch_sc_m6,tch_sc_m7,tch_sc_f1,tch_sc_f2,tch_sc_f3,tch_sc_f4,tch_sc_f5,tch_sc_f6,tch_sc_f7,tch_st_m1,tch_st_m2,tch_st_m3,tch_st_m4,tch_st_m5,tch_st_m6,tch_st_m7,tch_st_f1,tch_st_f2,tch_st_f3,tch_st_f4,tch_st_f5,tch_st_f6,tch_st_f7,trn_tch_m1,trn_tch_m2,trn_tch_m3,trn_tch_m4,trn_tch_m5,trn_tch_m6,trn_tch_m7,trn_tch_f1,trn_tch_f2,trn_tch_f3,trn_tch_f4,trn_tch_f5,trn_tch_f6,trn_tch_f7,prof_trn_tch_r,prof_trn_tch_p,days_nontch,tch_nontch
Unique_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2012-13_21_2129,2012-13,21,ORISSA ...,2129,KORAPUT ...,18,162,1529,2685,1376934.0,215490.17,16.37,1031.0,970.0,16.63,14.25,50.56,Low,38.92,21,ORISSA ...,2129,KORAPUT ...,2012-13,3544,2606,106,79,30,625,577,0,176,206,0,7,0,294,300,0,38,0,0,0,0,10,0,0,136,78,0,0,0,21,5,3,1283,804,1,25,3,167,86,84,927,601,0,14,0,165,86,73,1049,1000,38,33,7,390,458,181,218,180,56,12,18,136,129,30,24,18,4,0,2,11,27,14,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,2314,1541,46,34,14,491,528,1323,1140,53,50,16,399,263,0,0,0,0,0,0,0,79,79,5,0,0,20,44,42,52,2,2,0,19,42,0,0,0,0,0,0,0,476,303,1,5,0,67,53,193,166,0,7,2,43,27,580,337,4,4,1,108,34,163,146,1,7,4,34,18,790,566,0,18,0,101,17,403,320,0,29,0,44,9,6305,231,19,181
2013-14_21_2129,2013-14,21,ODISHA ...,2129,KORAPUT ...,18,177,1550,2736,1376934.0,215490.17,16.37,1031.0,970.0,16.63,14.25,50.56,Low,38.92,21,ODISHA ...,2129,KORAPUT ...,2013-14,3633,2648,118,105,41,965,661,0,183,275,20,13,0,279,314,0,25,17,0,0,0,10,0,0,127,61,1,1,0,16,5,35,943,671,3,22,3,139,63,407,793,531,5,16,2,125,79,555,959,952,35,44,13,420,509,739,181,179,45,12,21,137,156,188,21,10,6,0,1,12,28,30,0,0,3,0,0,0,0,1,1,1,0,0,0,0,0,0,1809,1315,55,39,24,479,570,1216,1090,43,56,16,370,270,0,0,0,0,0,0,0,592,336,16,7,0,235,64,224,199,24,16,1,170,71,0,0,0,0,0,0,0,481,329,3,10,4,106,69,218,182,0,8,4,56,35,591,371,5,7,1,138,40,200,155,2,7,3,47,24,688,472,9,9,0,95,24,266,251,2,9,0,33,9,5933,1258,17,126

In [ ]:
print("Preprocessed and scaled features for Koraput (as fed to the model):")

# Re-run the preprocessing steps for 'Koraput' to get the exact features
# (These steps are already inside predict_literacy_for_district, but we'll extract for inspection)

# 1. Find rows in df_raw_merged matching the district name
district_rows_raw = df_raw_merged[df_raw_merged['distname_x'].str.contains('Koraput', case=False, na=False)].copy()

# 2. Apply the same column drops as done for the training data
district_data_processed = district_rows_raw.drop(columns=col_to_drop, errors='ignore')

# 3. Ensure all required feature columns are present and in the correct order as X (training data)
training_feature_columns = X.columns.tolist()

# Drop any columns in district_data_processed that are not in training_feature_columns
extra_cols = [col for col in district_data_processed.columns if col not in training_feature_columns]
district_data_processed.drop(columns=extra_cols, inplace=True)

# Add any missing columns that were in training_feature_columns but not in district_data_processed
missing_cols_in_input = set(training_feature_columns) - set(district_data_processed.columns)
for c in missing_cols_in_input:
    district_data_processed[c] = np.nan # Fill with NaN, which will be imputed later

# Reorder columns to match X.columns
district_data_final = district_data_processed[training_feature_columns]

# 4. Impute missing numerical values using the stored medians from the training data
numerical_cols_to_impute = district_data_final.select_dtypes(include=np.number).columns
for col in numerical_cols_to_impute:
    if col in median_imputation_values:
        district_data_final[col] = district_data_final[col].fillna(median_imputation_values[col])

# 5. Scale the numerical features using the *fitted* scaler
cols_to_scale = [col for col in training_feature_columns if col in district_data_final.select_dtypes(include=np.number).columns]
district_data_final[cols_to_scale] = scaler.transform(district_data_final[cols_to_scale])

display(district_data_final)

Preprocessed and scaled features for Koraput (as fed to the model):

,distcd_x,blocks,clusters,villages,totschools,p_06_pop,p_urb_pop,sexratio,sexratio_06,growthrate,p_sc_pop,p_st_pop,female_lit,tch_govt2,tch_govt3,tch_govt6,tch_govt9,tch_pvt1,tch_pvt2,tch_pvt4,tch_pvt5,tch_pvt9,tch_un1,tch_un2,tch_un3,tch_un4,tch_un5,tch_un6,tch_un7,tch_un9,tch_bs1,tch_bs2,tch_bs3,tch_bs4,tch_bs5,tch_bs6,tch_bs7,tch_bs_p,tch_s1,tch_s2,tch_s3,tch_s4,tch_s5,tch_s6,tch_s_p,tch_hs1,tch_hs2,tch_hs3,tch_hs4,tch_hs5,tch_hs6,tch_hs7,tch_hs_p,tch_grad1,tch_grad2,tch_grad_p,tch_pgrad1,tch_pgrad2,tch_pgrad4,tch_pgrad6,tch_pgrad_p,tch_mph1,tch_mph2,tch_mph4,tch_mph5,tch_mph6,tch_mph7,tch_mph_p,tch_pd1,tch_pd2,tch_pd3,tch_pd4,tch_pd5,tch_pd6,tch_pd7,tch_pd_p,tch_eduqual_nr1,tch_eduqual_nr2,tch_eduqual_nr3,tch_eduqual_nr4,tch_eduqual_nr5,tch_eduqual_nr6,tch_eduqual_nr7,tch_eduqual_nr_p,tch_m1,tch_m4,tch_f1,tch_f2,tch_f3,tch_f4,tch_f5,tch_f6,tch_f7,tch_nr1,tch_nr2,tch_nr3,tch_nr4,tch_nr5,tch_nr6,tch_nr7,tch_m_p1,tch_m_p2,tch_m_p3,tch_m_p6,tch_m_p7,tch_f_p1,tch_f_p2,tch_f_p3,tch_f_p4,tch_f_p5,tch_f_p6,tch_f_p7,tch_nr_p1,tch_nr_p2,tch_nr_p3,tch_nr_p4,tch_nr_p5,tch_nr_p6,tch_nr_p7,tch_sc_m1,tch_sc_m2,tch_sc_m3,tch_sc_m4,tch_sc_m5,tch_sc_m6,tch_sc_m7,tch_sc_f1,tch_sc_f2,tch_sc_f3,tch_sc_f4,tch_sc_f5,tch_sc_f6,tch_sc_f7,tch_st_m1,tch_st_m2,tch_st_m3,tch_st_m4,tch_st_m5,tch_st_m6,tch_st_m7,tch_st_f1,tch_st_f2,tch_st_f3,tch_st_f4,tch_st_f5,tch_st_f6,tch_st_f7,trn_tch_m1,trn_tch_m2,trn_tch_m3,trn_tch_m4,trn_tch_m5,trn_tch_m6,trn_tch_m7,trn_tch_f1,trn_tch_f2,trn_tch_f3,trn_tch_f4,trn_tch_f5,trn_tch_f6,trn_tch_f7,prof_trn_tch_r,prof_trn_tch_p,days_nontch,tch_nontch
Unique_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2012-13_21_2129,0.435477,0.702701,0.327791,0.972606,0.329550,-0.178422,-0.442513,1.416173,1.15996,-0.08802,-0.06493,1.232051,-2.057104,0.353111,-0.103216,1.567165,-0.057653,-0.568928,-0.628131,-0.417761,-0.449822,-0.070194,-0.299834,-0.408914,-0.192014,-0.177828,-0.161116,-0.139066,-0.295949,-0.045741,0.282932,0.074591,-0.364172,-0.347761,-0.495357,0.132788,0.025483,-0.376454,0.824974,0.492814,-0.525181,-0.198536,-0.426116,2.250370,0.262511,-0.110586,-0.160805,-0.560239,-0.390370,-0.474021,0.519442,0.215527,-0.386842,-0.173491,-0.046335,-0.310424,-0.590538,-0.476851,-0.57248,-0.073592,-0.506340,0.006544,-0.100034,-0.573602,-0.316567,0.202958,0.983057,0.882149,-0.363713,-0.329612,-0.332487,-0.277519,-0.235602,-0.227151,-0.20909,2.068419,-0.123913,-0.166116,-0.102395,-0.074254,-0.073011,-0.121191,-0.113252,-0.085015,0.211664,-0.609034,-0.218923,-0.145597,-0.438563,-0.548330,-0.484513,0.143302,0.002912,-0.213126,-0.175638,-0.113562,-0.139723,-0.14038,-0.148428,-0.153516,-0.356555,-0.021211,-0.153897,0.141877,0.856997,-0.408122,-0.013613,-0.213650,-0.271820,-0.240524,0.082867,0.454605,-0.08562,-0.062919,-0.048698,-0.059102,-0.045907,0.0,-0.037704,0.300950,0.369019,-0.469098,-0.556680,-0.472464,0.439548,-0.041410,-0.153310,0.111685,-0.438048,-0.452266,-0.410060,0.408502,-0.043571,0.733841,0.734683,-0.294723,-0.334835,-0.433949,1.036704,0.026999,0.002278,0.226384,-0.353321,-0.233316,-0.334555,0.196316,0.062010,0.100087,0.10724,-0.167049,-0.440210,-0.402291,1.874044,-0.296142,-0.209840,-0.131122,-0.161313,-0.269645,-0.393926,0.384419,-0.294377,-0.316544,-0.289448,0.094583,-0.247136
2013-14_21_2129,0.435477,0.702701,0.475425,1.005716,0.364713,-0.178422,-0.442513,1.416173,1.15996,-0.08802,-0.06493,1.232051,-2.057104,0.370787,-0.077959,2.711764,-0.057653,-0.563417,-0.578781,-0.404881,-0.449822,-0.070194,-0.349082,-0.345930,-0.192014,-0.177828,-0.161116,-0.139066,-0.295949,-0.045741,0.221646,-0.026458,-0.335662,-0.325485,-0.495357,0.066525,0.025483,0.825829,0.449623,0.325165,-0.494167,-0.234819,-0.426116,1.777801,2.928789,-0.258991,-0.230385,-0.528443,-0.384614,-0.461722,0.236016,0.164098,0.952976,-0.240749,-0.086782,0.600101,-0.640624,-0.478372,-0.57248,-0.069955,0.179224,-0.080197,-0.231071,-0.573602,-0.322055,0.252051,1.035487,2.484820,-0.363713,-0.329612,1.598476,-0.277519,-0.235602,-0.227151,-0.20909,2.068419,-0.104089,-0.147043,-0.102395,-0.074254,-0.073011,-0.121191,-0.113252,-0.085015,-0.068461,-0.602981,-0.284209,-0.175650,-0.445992,-0.531895,-0.484513,0.093216,0.012324,-0.213126,-0.175638,-0.113562,-0.139723,-0.14038,-0.148428,-0.153516,0.777893,0.891904,0.175330,5.552206,1.398047,-0.027167,1.251943,0.015916,-0.013227,-0.232849,3.334851,0.952483,-0.08562,-0.062919,-0.048698,-0.059102,-0.045907,0.0,-0.037704,0.312577,0.462270,-0.441791,-0.519355,-0.456110,0.939663,0.082832,-0.069668,0.195366,-0.438048,-0.434985,-0.397287,0.677465,0.044844,0.760656,0.867437,-0.270161,-0.318954,-0.433949,1.439530,0.112407,0.131829,0.272625,-0.331191,-0.233316,-0.360329,0.420950,0.212255,-0.000896,-0.00343,-0.078224,-0.479344,-0.402291,1.734283,-0.258125,-0.381789,-0.208602,-0.151305,-0.424440,-0.393926,0.218396,-0.294377,-0.368796,1.161587,-0.035072,-0.295012

### Interactive District Literacy Prediction

In [ ]:
district_name_input = input("Enter the district name to predict its literacy rate: ")
predict_literacy_for_district(district_name_input)

Enter the district name to predict its literacy rate: rayagada
Found 2 entries for 'rayagada'. Predicting for each entry:
  - Unique ID: 2012-13_21_2127, Predicted Literacy: Low (Confidence: 89.00%)
  - Unique ID: 2013-14_21_2127, Predicted Literacy: Low (Confidence: 78.00%)

Random Forest Classifier (used for prediction) Accuracy on training data: 96.46%